### ISSUE TITLE
Unable to add closed exception dates

### ISSUE THREAD

**Issue by Pixinside** [OFFLINE-GmbH/oc-opening-hours-plugin#11]
Hello,

I'm unable to add exception full closed date as it needs an hour.

"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'hours' cannot be null (SQL: insert into `offline_openinghours_exceptions` (`location_id`, `for_date`, `note`, `yearly`, `hours`, `updated_at`, `created_at`) values (1, 2021-12-31 15:24:00, , 0, ?, 2021-11-29 16:24:03, 2021-11-29 16:24:03))" on line 669 of /Users/casashock/Documents/NovaProjects/hydro/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by tobias-kuendig** [comment]
Thank you for reporting this issue! Please update to verison 1.0.14 of the plugin for a fix.

**Comment by Pixinside** [comment]
Works in backend!
But I have now this issue in the frontend:

Argument 1 passed to OFFLINE\OpeningHours\Models\Location::toTimeRange() must be of the type array, null given, called in /Users/casashock/Documents/NovaProjects/hydro/plugins/offline/openinghours/models/Location.php on line 70

~/plugins/offline/openinghours/classes/DateUtils.php line 83

**Comment by tobias-kuendig** [comment]
Could you update the plugin again and see if it works now?

**Comment by Pixinside** [comment]
Works like a charm!!! Really nice plugin!
