### ISSUE TITLE
An issue with opening hours setup

### ISSUE THREAD

**Issue by Jerry-gif** [OFFLINE-GmbH/oc-opening-hours-plugin#3]
Hi, very useful plugin, but I'm not able to setup proper time for opening hours. It allways shows time from 08:00 to 17:00.

**Comment by tobias-kuendig** [comment]
Where does it show that? What's your setup? Do you have some code? Without more details I cannot help you.

**Comment by Jerry-gif** [comment]
I'm sorry, it was my fault, wrong time settings on server
